# Generated by Django 2.0.2 on 2018-05-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('subject', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=5000)),
            ],
        ),
    ]
